# Alle retigheder af dette plugin ejes af yzhy.
# Videresalg af dette plugin er ikke tilladt.
# Kontakt yzhy#0722 på discord for hjælp & forslag.

#Reload med /combat reload!

Combat:
  Enabled: true #Skal combat være enabled?
  Tid: 15 #Tid man kommer i combat. (i sekunder)

ActionBar:
  Enabled: true #Skal den vise en actionbar til spilleren?
  Tekst:
    ICombat: '&4&l[!] &7Du er i combat i &f%tid%s&7!' #Brug %tid% for at få antallet sekunder man skal komme i combat! %attacker% of %victim% kan også bruges!
    UdeCombat: '&4&l[!] &7Du er nu ude af combat!'

Bypass:
  Enabled: true #Skal folk med permissionen bypass combat?
  Permission: 'Combat.Bypass' #Bemærk at OPs også har denne permission!

Beskeder:
  Enabled: true #Skal den sende beskeder?
  CombatEnable: '&4&l[!] &7Du er nu i combat!' # Du kan også bruge %tid% i denne besked!
  CombatDisable: '&4&l[!] &7Du er nu ude af combat!' # Du kan også bruge %tid% i denne besked!
  CombatCommand:
    CombatEnabled: '&4&l[!] &7Du er i combat i &f%tid%s&7.'
    CombatDisabled: '&4&l[!] &7Du er ikke i combat!'
  BroadcastLogOut:
    Enabled: true
    Message: '&4&l[!] &7Spilleren &f%player%&7 loggede ud i combat!'

# API HJÆLP
# Skript & skript-reflect eksempel!

#Import:
  #dk.yzhy.utils.API

# Du kan bruge:
  #API.getCombat(Player) #Få en spillers combat-tid.
  #API.setCombat(Player, 15) #Sætter spillerens combat til 15, tallet kan ændres.
  #API.inCombat(Player) Returner true hvis spilleren er i combat, og returner false hvis ikke.

